{% set name = "fast-dds" %}
{% set version = "2.3.3" %}
{% set major_minor_version = version.split('.')[0] + '.' + version.split('.')[1] %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/eProsima/Fast-DDS/archive/v{{ version }}.tar.gz
    sha256: 5ebf27d810c6ab68eef7d42937cd421d85e50509ae96883239979a1b3a2f4f82

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - ninja
    - pkg-config
  host:
    - fast-cdr
    - asio
    - tinyxml2
    - openssl
    - foonathan-memory
  run:
    - fast-cdr
    - asio
    - tinyxml2
    - openssl
    - foonathan-memory
  run_constrained:
    # disallow installation alongside fast-rtps
    - fast-rtps 99999999 fast_rtps_collides_with_fast_dds

test:
  commands:
    - if not exist %LIBRARY_PREFIX%\\bin\\fastrtps-{{ major_minor_version }}.dll exit 1  # [win]
    - test -f $PREFIX/lib/libfastrtps${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/fastdds/dds/domain/DomainParticipantFactory.hpp  # [unix]
    - test -f $PREFIX/include/fastdds/rtps/Endpoint.h  # [unix]
    - test -f $PREFIX/include/fastrtps/transport/UDPTransportDescriptor.h  # [unix]

about:
  home: https://github.com/eProsima/Fast-RTPS
  license: Apache-2.0
  license_file: LICENSE
  summary: |
    eProsima Fast DDS (formerly Fast-RTPS)

extra:
  recipe-maintainers:
    - wolfv
    - MiguelCompany
    - EduPonz
